#!/bin/bash

sed --regexp-extended \
    --expression="

      # TITLE=...
      s/^TITLE=(.+)\(([^,]+),[[:space:]]+([^:]+):[[:space:]]+([^\(\)]+)\)$/TITLE=\1(\3, \2: \4)/

      # AUTHOR=...
      s/^AUTHOR=([^,]+),[[:space:]]+(.+)/AUTHOR=\2, \1/

    "

exit 0

