#!/bin/bash

find "../audio/ZeitZeichen/"                               \
     -type      "f"                                        \
     -regextype "posix-extended"                           \
     -regex     ".+\.[Mm][Pp]3$"                           \
| sort                                                     \
| xargs -L 100 id3v2 -l                                    \
| sed -nre "s/^TIT2[[:space:]][^:]+:[[:space:]]+(.+)/\1/p" \
| sed -re "s/[^[:alnum:]]+/ /g"                            \
| sed -re "s/ +/ /g"                                       \
| tr ' ' '\n'                                              \
| sed -re "/^.?.?$/d"                                      \
| sed -re "/^[[:digit:]]+$/d"                              \
| sort -u

exit 0

