#!/bin/bash

# filenames
readonly PLIST="last100.m3u"
readonly XLIST="selecta.m3u"

# call daily100 to create basic playlist
if ! ./daily100 "$@" > "$PLIST" ; then

  # stop here
  exit 1

fi

# add extra episodes
if [ -s "$XLIST" ] ; then

  sed -i -re "1 i #XLIST" "$PLIST"
  sed -i -re "1 r $XLIST" "$PLIST"
  sed -i -re "1 d"        "$PLIST"

fi

# copy playlist items
plcopy -g "Speech"                       \
       -a "Podcast"                      \
       -b "$(date "+Last100: %Y-%m-%d")" \
       -i "../images/podcast.png"        \
       "$PLIST"                          \
       "$(date "+Last100-%Y-%m-%d")"

# signalize success
exit 0

