#!/bin/bash

# get all words from ZeitZeichen title tags
find "/home/xi/podcast/audio/ZeitZeichen/" \
     -type f                               \
     -regextype "posix-extended"           \
     -regex ".+\.[Mm][Pp]3$"               \
| xargs -L1 -I'{}' id3v2 -R '{}'           \
| sed -nre "s/^TIT2: //p"                  \
| sed -re  "s/[[:space:]]+/ /g"            \
| sed -re  "s/^[^:]+: //"                  \
| sed -re  "s/\([^\)]+\)$//"               \
| sed -re  "s/[^[:alnum:]]+/ /g"           \
| sed -re  "s/^ // ; s/ $//"               \
| tr ' ' '\n'                              \
| sed -re "/^..?$/ d"                      \
| sed -re "/^[[:digit:]]+$/ d"             \
| sort -u

exit 0

